name: release
on:
  workflow_dispatch:
  push:
    branches:
    - main

permissions:
  id-token: write

jobs: 
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'

    - name: Install dependencies
      shell: bash
      run: |
        cd src
        go get src

    - name: Build
      run: |
        cd src
        GOOS=windows
        go build -o parser.exe
        GOOS=linux
        go build -o parser

    - name: Test
      run: go test

    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: Azure CLI script
      uses: azure/cli@v2
      env:
        ACCOUNT_NAME: nnstg
        CONTAINER_NAME: fcpxml
      with:
        azcliversion: latest
        inlineScript: |
          az account show
          az storage blob upload -f src/parser.exe --account-name $ACCOUNT_NAME --container-name $CONTAINER_NAME
          az storage blob upload -f src/parser --account-name $ACCOUNT_NAME --container-name $CONTAINER_NAME